/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/rf-button/rf-button";
import { ChipToggleDetail } from "./components/rf-chip/rf-chip";
import { DaySlotDetail } from "./components/rf-day-slot/rf-day-slot";
import { RatingChangeDetail } from "./components/rf-rating/rf-rating";
import { FavoriteToggleDetail, ViewRecipeDetail } from "./components/rf-recipe-card/rf-recipe-card";
import { SearchChangeDetail } from "./components/rf-search-bar/rf-search-bar";
export { ButtonVariant } from "./components/rf-button/rf-button";
export { ChipToggleDetail } from "./components/rf-chip/rf-chip";
export { DaySlotDetail } from "./components/rf-day-slot/rf-day-slot";
export { RatingChangeDetail } from "./components/rf-rating/rf-rating";
export { FavoriteToggleDetail, ViewRecipeDetail } from "./components/rf-recipe-card/rf-recipe-card";
export { SearchChangeDetail } from "./components/rf-search-bar/rf-search-bar";
export namespace Components {
    interface RfButton {
        /**
          * Disables the button and prevents clicks.
          * @default false
         */
        "disabled": boolean;
        /**
          * Native button type, useful when used inside a form.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface RfChip {
        /**
          * Text shown inside the chip.
         */
        "label": string;
        /**
          * Whether the chip is currently active/selected.
          * @default false
         */
        "selected": boolean;
    }
    interface RfDaySlot {
        /**
          * Day of the week this slot represents, e.g. "Monday".
         */
        "day": string;
        /**
          * Whether this day currently has no recipe assigned.
          * @default true
         */
        "empty": boolean;
        /**
          * Thumbnail image of the recipe assigned to this day, if any.
         */
        "recipeImage"?: string;
        /**
          * Title of the recipe assigned to this day, if any.
         */
        "recipeTitle"?: string;
    }
    interface RfModal {
        /**
          * Heading text shown at the top of the modal.
          * @default ''
         */
        "heading": string;
        /**
          * Controls whether the modal is visible.
          * @default false
         */
        "open": boolean;
    }
    interface RfRating {
        /**
          * When true, the rating is display-only and cannot be changed by the user.
          * @default false
         */
        "readonly": boolean;
        /**
          * Current rating value, 0-5.
          * @default 0
         */
        "value": number;
    }
    interface RfRecipeCard {
        /**
          * Recipe area/cuisine, e.g. "Italian".
          * @default ''
         */
        "area": string;
        /**
          * Recipe category, e.g. "Seafood".
          * @default ''
         */
        "category": string;
        /**
          * Recipe thumbnail image URL.
          * @default ''
         */
        "image": string;
        /**
          * Whether this recipe was created locally by the user (shows a "My Recipe" badge).
          * @default false
         */
        "isCustom": boolean;
        /**
          * Whether this recipe is currently in the user's favorites.
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Unique identifier for the recipe (API id or local-* id).
         */
        "mealId": string;
        /**
          * Recipe title.
          * @default ''
         */
        "recipeTitle": string;
    }
    interface RfSearchBar {
        /**
          * Debounce delay, in ms, before searchChange is emitted after typing stops.
          * @default 300
         */
        "debounce": number;
        /**
          * Placeholder text for the input.
          * @default 'Search...'
         */
        "placeholder": string;
        /**
          * Current value of the search input (controlled from outside).
          * @default ''
         */
        "value": string;
    }
}
export interface RfChipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfChipElement;
}
export interface RfDaySlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfDaySlotElement;
}
export interface RfModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfModalElement;
}
export interface RfRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRatingElement;
}
export interface RfRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRecipeCardElement;
}
export interface RfSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfSearchBarElement;
}
declare global {
    interface HTMLRfButtonElement extends Components.RfButton, HTMLStencilElement {
    }
    var HTMLRfButtonElement: {
        prototype: HTMLRfButtonElement;
        new (): HTMLRfButtonElement;
    };
    interface HTMLRfChipElementEventMap {
        "chipToggle": ChipToggleDetail;
    }
    interface HTMLRfChipElement extends Components.RfChip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfChipElementEventMap>(type: K, listener: (this: HTMLRfChipElement, ev: RfChipCustomEvent<HTMLRfChipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfChipElementEventMap>(type: K, listener: (this: HTMLRfChipElement, ev: RfChipCustomEvent<HTMLRfChipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfChipElement: {
        prototype: HTMLRfChipElement;
        new (): HTMLRfChipElement;
    };
    interface HTMLRfDaySlotElementEventMap {
        "addMeal": DaySlotDetail;
        "removeMeal": DaySlotDetail;
    }
    interface HTMLRfDaySlotElement extends Components.RfDaySlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfDaySlotElementEventMap>(type: K, listener: (this: HTMLRfDaySlotElement, ev: RfDaySlotCustomEvent<HTMLRfDaySlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfDaySlotElementEventMap>(type: K, listener: (this: HTMLRfDaySlotElement, ev: RfDaySlotCustomEvent<HTMLRfDaySlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfDaySlotElement: {
        prototype: HTMLRfDaySlotElement;
        new (): HTMLRfDaySlotElement;
    };
    interface HTMLRfModalElementEventMap {
        "modalClose": void;
    }
    interface HTMLRfModalElement extends Components.RfModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfModalElement: {
        prototype: HTMLRfModalElement;
        new (): HTMLRfModalElement;
    };
    interface HTMLRfRatingElementEventMap {
        "ratingChange": RatingChangeDetail;
    }
    interface HTMLRfRatingElement extends Components.RfRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRatingElementEventMap>(type: K, listener: (this: HTMLRfRatingElement, ev: RfRatingCustomEvent<HTMLRfRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRatingElementEventMap>(type: K, listener: (this: HTMLRfRatingElement, ev: RfRatingCustomEvent<HTMLRfRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRatingElement: {
        prototype: HTMLRfRatingElement;
        new (): HTMLRfRatingElement;
    };
    interface HTMLRfRecipeCardElementEventMap {
        "favoriteToggle": FavoriteToggleDetail;
        "viewRecipe": ViewRecipeDetail;
    }
    interface HTMLRfRecipeCardElement extends Components.RfRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRecipeCardElement: {
        prototype: HTMLRfRecipeCardElement;
        new (): HTMLRfRecipeCardElement;
    };
    interface HTMLRfSearchBarElementEventMap {
        "searchChange": SearchChangeDetail;
    }
    interface HTMLRfSearchBarElement extends Components.RfSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfSearchBarElement: {
        prototype: HTMLRfSearchBarElement;
        new (): HTMLRfSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "rf-button": HTMLRfButtonElement;
        "rf-chip": HTMLRfChipElement;
        "rf-day-slot": HTMLRfDaySlotElement;
        "rf-modal": HTMLRfModalElement;
        "rf-rating": HTMLRfRatingElement;
        "rf-recipe-card": HTMLRfRecipeCardElement;
        "rf-search-bar": HTMLRfSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface RfButton {
        /**
          * Disables the button and prevents clicks.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Native button type, useful when used inside a form.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface RfChip {
        /**
          * Text shown inside the chip.
         */
        "label": string;
        /**
          * Fired whenever the chip is clicked, with the new selected state.
         */
        "onChipToggle"?: (event: RfChipCustomEvent<ChipToggleDetail>) => void;
        /**
          * Whether the chip is currently active/selected.
          * @default false
         */
        "selected"?: boolean;
    }
    interface RfDaySlot {
        /**
          * Day of the week this slot represents, e.g. "Monday".
         */
        "day": string;
        /**
          * Whether this day currently has no recipe assigned.
          * @default true
         */
        "empty"?: boolean;
        /**
          * Fired when the user wants to assign a recipe to this day.
         */
        "onAddMeal"?: (event: RfDaySlotCustomEvent<DaySlotDetail>) => void;
        /**
          * Fired when the user removes the recipe assigned to this day.
         */
        "onRemoveMeal"?: (event: RfDaySlotCustomEvent<DaySlotDetail>) => void;
        /**
          * Thumbnail image of the recipe assigned to this day, if any.
         */
        "recipeImage"?: string;
        /**
          * Title of the recipe assigned to this day, if any.
         */
        "recipeTitle"?: string;
    }
    interface RfModal {
        /**
          * Heading text shown at the top of the modal.
          * @default ''
         */
        "heading"?: string;
        /**
          * Fired when the user requests the modal to close (backdrop click, close button, or Escape).
         */
        "onModalClose"?: (event: RfModalCustomEvent<void>) => void;
        /**
          * Controls whether the modal is visible.
          * @default false
         */
        "open"?: boolean;
    }
    interface RfRating {
        /**
          * Fired when the user picks a new rating (only when readonly is false).
         */
        "onRatingChange"?: (event: RfRatingCustomEvent<RatingChangeDetail>) => void;
        /**
          * When true, the rating is display-only and cannot be changed by the user.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Current rating value, 0-5.
          * @default 0
         */
        "value"?: number;
    }
    interface RfRecipeCard {
        /**
          * Recipe area/cuisine, e.g. "Italian".
          * @default ''
         */
        "area"?: string;
        /**
          * Recipe category, e.g. "Seafood".
          * @default ''
         */
        "category"?: string;
        /**
          * Recipe thumbnail image URL.
          * @default ''
         */
        "image"?: string;
        /**
          * Whether this recipe was created locally by the user (shows a "My Recipe" badge).
          * @default false
         */
        "isCustom"?: boolean;
        /**
          * Whether this recipe is currently in the user's favorites.
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Unique identifier for the recipe (API id or local-* id).
         */
        "mealId": string;
        /**
          * Fired when the favorite button is clicked.
         */
        "onFavoriteToggle"?: (event: RfRecipeCardCustomEvent<FavoriteToggleDetail>) => void;
        /**
          * Fired when the card body is clicked to open the recipe details.
         */
        "onViewRecipe"?: (event: RfRecipeCardCustomEvent<ViewRecipeDetail>) => void;
        /**
          * Recipe title.
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface RfSearchBar {
        /**
          * Debounce delay, in ms, before searchChange is emitted after typing stops.
          * @default 300
         */
        "debounce"?: number;
        /**
          * Fired with the current query after the debounce window elapses.
         */
        "onSearchChange"?: (event: RfSearchBarCustomEvent<SearchChangeDetail>) => void;
        /**
          * Placeholder text for the input.
          * @default 'Search...'
         */
        "placeholder"?: string;
        /**
          * Current value of the search input (controlled from outside).
          * @default ''
         */
        "value"?: string;
    }

    interface RfButtonAttributes {
        "variant": ButtonVariant;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface RfChipAttributes {
        "label": string;
        "selected": boolean;
    }
    interface RfDaySlotAttributes {
        "day": string;
        "recipeTitle": string;
        "recipeImage": string;
        "empty": boolean;
    }
    interface RfModalAttributes {
        "open": boolean;
        "heading": string;
    }
    interface RfRatingAttributes {
        "value": number;
        "readonly": boolean;
    }
    interface RfRecipeCardAttributes {
        "mealId": string;
        "recipeTitle": string;
        "image": string;
        "category": string;
        "area": string;
        "isFavorite": boolean;
        "isCustom": boolean;
    }
    interface RfSearchBarAttributes {
        "placeholder": string;
        "value": string;
        "debounce": number;
    }

    interface IntrinsicElements {
        "rf-button": Omit<RfButton, keyof RfButtonAttributes> & { [K in keyof RfButton & keyof RfButtonAttributes]?: RfButton[K] } & { [K in keyof RfButton & keyof RfButtonAttributes as `attr:${K}`]?: RfButtonAttributes[K] } & { [K in keyof RfButton & keyof RfButtonAttributes as `prop:${K}`]?: RfButton[K] };
        "rf-chip": Omit<RfChip, keyof RfChipAttributes> & { [K in keyof RfChip & keyof RfChipAttributes]?: RfChip[K] } & { [K in keyof RfChip & keyof RfChipAttributes as `attr:${K}`]?: RfChipAttributes[K] } & { [K in keyof RfChip & keyof RfChipAttributes as `prop:${K}`]?: RfChip[K] } & OneOf<"label", RfChip["label"], RfChipAttributes["label"]>;
        "rf-day-slot": Omit<RfDaySlot, keyof RfDaySlotAttributes> & { [K in keyof RfDaySlot & keyof RfDaySlotAttributes]?: RfDaySlot[K] } & { [K in keyof RfDaySlot & keyof RfDaySlotAttributes as `attr:${K}`]?: RfDaySlotAttributes[K] } & { [K in keyof RfDaySlot & keyof RfDaySlotAttributes as `prop:${K}`]?: RfDaySlot[K] } & OneOf<"day", RfDaySlot["day"], RfDaySlotAttributes["day"]>;
        "rf-modal": Omit<RfModal, keyof RfModalAttributes> & { [K in keyof RfModal & keyof RfModalAttributes]?: RfModal[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `attr:${K}`]?: RfModalAttributes[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `prop:${K}`]?: RfModal[K] };
        "rf-rating": Omit<RfRating, keyof RfRatingAttributes> & { [K in keyof RfRating & keyof RfRatingAttributes]?: RfRating[K] } & { [K in keyof RfRating & keyof RfRatingAttributes as `attr:${K}`]?: RfRatingAttributes[K] } & { [K in keyof RfRating & keyof RfRatingAttributes as `prop:${K}`]?: RfRating[K] };
        "rf-recipe-card": Omit<RfRecipeCard, keyof RfRecipeCardAttributes> & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes]?: RfRecipeCard[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `attr:${K}`]?: RfRecipeCardAttributes[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `prop:${K}`]?: RfRecipeCard[K] } & OneOf<"mealId", RfRecipeCard["mealId"], RfRecipeCardAttributes["mealId"]>;
        "rf-search-bar": Omit<RfSearchBar, keyof RfSearchBarAttributes> & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes]?: RfSearchBar[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `attr:${K}`]?: RfSearchBarAttributes[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `prop:${K}`]?: RfSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-button": LocalJSX.IntrinsicElements["rf-button"] & JSXBase.HTMLAttributes<HTMLRfButtonElement>;
            "rf-chip": LocalJSX.IntrinsicElements["rf-chip"] & JSXBase.HTMLAttributes<HTMLRfChipElement>;
            "rf-day-slot": LocalJSX.IntrinsicElements["rf-day-slot"] & JSXBase.HTMLAttributes<HTMLRfDaySlotElement>;
            "rf-modal": LocalJSX.IntrinsicElements["rf-modal"] & JSXBase.HTMLAttributes<HTMLRfModalElement>;
            "rf-rating": LocalJSX.IntrinsicElements["rf-rating"] & JSXBase.HTMLAttributes<HTMLRfRatingElement>;
            "rf-recipe-card": LocalJSX.IntrinsicElements["rf-recipe-card"] & JSXBase.HTMLAttributes<HTMLRfRecipeCardElement>;
            "rf-search-bar": LocalJSX.IntrinsicElements["rf-search-bar"] & JSXBase.HTMLAttributes<HTMLRfSearchBarElement>;
        }
    }
}
